### ISSUE TITLE
boot.initrd.systemd.enable broken with asahi kernel config 

### ISSUE THREAD

**Issue by psanford** [tpwrules/nixos-apple-silicon#103]
I wanted to set `boot.initrd.systemd.enable = true` to enable unlocking my luks2 root volume with a fido2 key. 

`boot.initrd.systemd` adds a couple of kernel modules to `initrd.availableKernelModules` including `tpm-tis` and `tpm-crb`: https://github.com/nixos/nixpkgs/blob/a59124d7d492bb319cecd7ed26c5a4c29154ccb3/nixos/modules/system/boot/systemd/initrd.nix#L343-L348

Neither of those modules are currently complied with the apple-silicon kernel so this failed. 

It would be nice to add these modules so this works out of the box.

I worked around this issue by setting the following in my kernel extraConfig:
```
          ACPI y
          TCG_TPM y
          TCG_TIS m
          TCG_CRB m
```

**Comment by tpwrules** [comment]
This is fixed in the upcoming release.
