### ISSUE TITLE
extraConfig use does not align with nixpkgs

### ISSUE THREAD

**Issue by RossComputerGuy** [tpwrules/nixos-apple-silicon#106]
According to the documentation listed on search.nixos.org, the `extraConfig` option in `boot.kernelPatches` is a direct `CONFIG_*` line. nixos-apple-silicon adds in `CONFIG_` as shown [here](https://github.com/tpwrules/nixos-apple-silicon/blob/096dc63e5426e17f70b4a8bf7716c3dd3430ba8c/apple-silicon-support/packages/linux-asahi/default.nix#L44). This will cause issues when the required config is checked.

# Example

Fails asserts due to a required config check:
```nix
  boot.kernelPatches = [{
    name = "waydroid";
    patch = null;
    extraConfig = ''
      ANDROID_BINDER_IPC y
      ANDROID_BINDERFS y
      ANDROID_BINDER_DEVICES binder,hwbinder,vndbinder
      ASHMEM y
    '';
  }];
```

Evaluates but does not function properly:
```nix
  boot.kernelPatches = [{
    name = "waydroid";
    patch = null;
    extraConfig = ''
      CONFIG_ANDROID_BINDER_IPC y
      CONFIG_ANDROID_BINDERFS y
      CONFIG_ANDROID_BINDER_DEVICES binder,hwbinder,vndbinder
      CONFIG_ASHMEM y
    '';
  }];
```

Works:
```nix
  boot.kernelPatches = [{
    name = "waydroid";
    patch = null;
    extraConfig = ''
      ANDROID_BINDER_IPC y
      ANDROID_BINDERFS y
      ANDROID_BINDER_DEVICES binder,hwbinder,vndbinder
      CONFIG_ASHMEM y
      CONFIG_ANDROID_BINDERFS y
      CONFIG_ANDROID_BINDER_IPC y
    '';
  }];
```

**Comment by tpwrules** [comment]
I am fairly certain the documentation is buggy there. For instance, in [nixpkgs itself](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/nixos/modules/misc/crashdump.nix#L67-L71), `CONFIG_` is not included when writing stuff in `extraConfig`. This is what I assumed and what the wiki says too.

What exact assertion is failing? Maybe that assertion is also incorrect, or there is a bug between that line you point to (which is correct and necessary to make the proper `.config`) and the assertion.

**Comment by RossComputerGuy** [comment]
```
error:
       Failed assertions:
       - CONFIG_ANDROID_BINDER_IPC is not enabled!
       - CONFIG_ANDROID_BINDERFS is not enabled!
       - CONFIG_ASHMEM is not enabled!
```

**Comment by tpwrules** [comment]
This has been fixed. The documentation is wrong and there was also a bug in nixos-apple-silicon.

**Comment by TheButlah** [comment]
I am getting 
```
Failed assertions:
       - CONFIG_ANDROID_BINDER_IPC is not enabled!
       - CONFIG_ANDROID_BINDERFS is not enabled!
 ```
when I try to add `virtualisation.waydroid.enable = true` to my nixos-apple-silicon machine.

Config is [here](https://github.com/TheButlah/nix/blob/d375e80f5a5f4f14c180d23d30c3c055bd5301af/machines/ryan-wld-asahi/configuration.nix) (I haven't committed the additional one-line change above though).
