### ISSUE TITLE
Add official support for speakers

### ISSUE THREAD

**Issue by diamondburned** [tpwrules/nixos-apple-silicon#119]
With the release of the [SW:Speakers](https://github.com/AsahiLinux/docs/wiki/SW:Speakers) wiki page, Asahi Linux now officially supports the Macbook Air M1 13" speakers (J313). This issue tracks the addition of this into nixos-apple-silicon.

Progress:

- [x] Asahi Linux 6.5-25 or later
- [x] alsa-ucm-conf-asahi
- [x] asahi-audio
- [x] speakersafetyd
- [x] bankstown
- [x] LSP plugins LV2 (how?)
- [x] Pipewire v0.3.84 (only in `staging` Nixpkgs atm)
- [x] Pipewire module-filter-chain-lv2
- [x] Wireplumber v0.4.15
- [x] Wireplumber w/ policy-dsp patch

Blocking Items:

- [x] https://github.com/chadmed/bankstown/pull/3
- [ ] Wait for upstream [AsahiLinux/PKGBUILDs](https://github.com/AsahiLinux/PKGBUILDs) to bump kernel version to `6.5-25` or later, or track the [Asahi Linux Fedora COPR](https://copr.fedorainfracloud.org/coprs/g/asahi/kernel/) instead
- [x] Wait for Pipewire v0.3.84 or newer to be merged into NixOS Unstable
- [ ] Add the needed modules into this repository (`hardware.asahi.enableSpeakers = true`)

Relevant issue: https://github.com/tpwrules/nixos-apple-silicon/issues/100

My current implementation: https://github.com/diamondburned/dotfiles/tree/hackadoll3/Scripts/nix/machines/lilyhoshii/cfg/speakers

**Comment by sequencer** [comment]
alarm is doomed :(

**Comment by tpwrules** [comment]
Thanks for inventorying this and providing a direction.

We will probably have to wait for Pipewire to progress through staging, but I'll do some experiments and see if we can just move it forward for a bit.

I'm also doing some studying on how to best account for the upstream migration away from Arch Linux but I don't have an answer right now.

**Comment by RossComputerGuy** [comment]
Pipewire v0.3.84 is merged into unstable and master as of today, though the v0.3.85 PR was opened almost a week ago and it's in unstable right now. I'm gonna see if I can reproduce getting speaker support in my setup today.

**Comment by yu-re-ka** [comment]
https://github.com/NixOS/nixpkgs/pull/274504

**Comment by yu-re-ka** [comment]
Also my own take on this in #122

**Comment by RossComputerGuy** [comment]
@vector1dev So I did get it added in but I found out that my device isn't supported yet. Mine uses j314 but only j313 is supported which is the MBA and I have a MBP.

**Comment by tpwrules** [comment]
> [NixOS/nixpkgs#274504](https://github.com/NixOS/nixpkgs/pull/274504)

Good to see that there's a release for my machine now so that I can properly test.

Should we just have this fix in our overlay for now, until the release comes out? That would get speakers to users a little quicker.

**Comment by yu-re-ka** [comment]
> Mine uses j314 but only j313 is supported which is the MBA and I have a MBP.

MacBook Pro J314 is also supported, but all of them need to be opted into by the distro/user by telling the kernel to enable audio.

**Comment by RossComputerGuy** [comment]
> but all of them need to be opted into by the distro/user by telling the kernel to enable audio.

How exactly is that done?

**Comment by yu-re-ka** [comment]
@RossComputerGuy please read the following chat log carefully: https://oftc.irclog.whitequark.org/asahi-dev/2023-10-28

**Comment by tpwrules** [comment]
We are working on this and hope to have a solution soon. Thanks for the patience.

**Comment by tpwrules** [comment]
Done in the latest release.
