### ISSUE TITLE
Feature parity with Fedora Asahi?

### ISSUE THREAD

**Issue by themg95** [tpwrules/nixos-apple-silicon#120]
After using Fedora Asahi for a while, I've found out about this project and am thinking of switching to it. However, I'm concerned that I will lose some recent features like OpenGL 3.3 support. 

In a few issues, asahi-edge is mentioned which leads me to believe that this project pulls from Asahi Arch and not Fedora Asahi but I'm not sure.

Does this project directly pull from Fedora Asahi and if so how behind is it?

**Comment by rowanG077** [comment]
Aarch is not that far behind currently. I think the only missing main feature at this time is HDMI out support for connecting displays. This is available in Fedora but not yet in Aarch (and also not in nixos).

**Comment by sequencer** [comment]
> Aarch is not that far behind currently. I think the only missing main feature at this time is HDMI out support for connecting displays. This is available in Fedora but not yet in Aarch (and also not in nixos).

Not only HDMI, Audio support is already on the mainstream as well. AFAIK, Asahi devs are not using alarm at all.

**Comment by tpwrules** [comment]
The information previous is mostly correct. I haven't figured out where to focus to determine the changes in Fedora so that's primarily why we are lagging. I'm working on that but it may still be a bit.

**Comment by zzywysm** [comment]
> The information previous is mostly correct. I haven't figured out where to focus to determine the changes in Fedora so that's primarily why we are lagging. I'm working on that but it may still be a bit.

All such info can be found at:
https://src.fedoraproject.org/group/asahi-sig
https://copr.fedorainfracloud.org/groups/g/asahi/coprs/

**Comment by tpwrules** [comment]
We are now officially tracking features and packages from Fedora Asahi Remix. Speaker support is, however, still in the pipeline.
