### ISSUE TITLE
apple-silicon-support/packages/linux-asahi/rust-bindgen-version.patch: Breaks POSIX

### ISSUE THREAD

**Issue by Kreyren** [tpwrules/nixos-apple-silicon#124]
https://github.com/tpwrules/nixos-apple-silicon/blob/14b327ca47703c376ebb82ba16dc42ca2baa57d8/apple-silicon-support/packages/linux-asahi/rust-bindgen-version.patch#L9-L11

There is a good reason why it's using `grep -F | grep -oE` as that is POSIX compatible (thus why it's .sh instead of .bash) so that it can be called from a shell that doesn't support dynamic linking.. Using `grep -oP` breaks that

**Comment by tpwrules** [comment]
This patch has been removed so any issues this cause should now be fixed.
