### ISSUE TITLE
Bad sound quality MacBook Air M2

### ISSUE THREAD

**Issue by ivabus** [tpwrules/nixos-apple-silicon#130]
Probably happened of misconfiguration of asahi-audio package in [modules/sound](https://github.com/tpwrules/nixos-apple-silicon/blob/feb12e2f0c8500b513de27b6095709bee609cf8a/apple-silicon-support/modules/sound/default.nix#L51)

WirePlumber and PipeWire should use their own configuration files from asahi-audio package, not from ALSA UCM

**Comment by tpwrules** [comment]
Embarrassed that I missed this. Thanks for tracking this down and reporting it. Fixed in the latest release.

**Comment by pawalt** [comment]
@tpwrules thanks for the quick fix here! Hijacking this thread to say thanks for all the hard work - it's so much appreciated. I was genuinely shocked when I just ran `nix flake update && switch` and my speakers just worked after a reboot :)
