### ISSUE TITLE
Add tiny-dfr package to support touchbars on 13-inch MBPs

### ISSUE THREAD

**Issue by zzywysm** [tpwrules/nixos-apple-silicon#137]
Fedora Asahi Remix ships a package called tiny-dfr that provides a basic function-key row on the MBP touchbar.

For feature parity, this project should ship the same code.

https://github.com/WhatAmISupposedToPutHere/tiny-dfr
https://src.fedoraproject.org/rpms/rust-tiny-dfr

**Comment by alyssais** [comment]
https://github.com/NixOS/nixpkgs/pull/277549

I had to enable CONFIG_INPUT_TOUCHSCREEN for input to work.

**Comment by zzywysm** [comment]
> I had to enable CONFIG_INPUT_TOUCHSCREEN for input to work.

What an amazing coincidence that someone filed https://github.com/tpwrules/nixos-apple-silicon/pull/134 !

😉

**Comment by tpwrules** [comment]
I've enabled that config option for convenience. I'm deferring to upstream on the package itself, partially because I don't have that hardware to test with.

**Comment by zzywysm** [comment]
Did you also enable CONFIG_TOUCHSCREEN_APPLE_Z2=m?  That's the actual driver for the touchbar, of which CONFIG_INPUT_TOUCHSCREEN is a prerequisite.

**Comment by tpwrules** [comment]
Yes, I did.

**Comment by tpwrules** [comment]
This seems better to have and maintain in nixpkgs. I have no way to test the package.
