### ISSUE TITLE
Making vscode cpptools work

### ISSUE THREAD

**Issue by rowanG077** [tpwrules/nixos-apple-silicon#144]
A month ago I made vscode cpptools plugin work on Asahi and made a PR https://github.com/NixOS/nixpkgs/pull/273416 unfortunately it sits there unreviewed. Since people here are probably interested in this I hope someone could review it and possibly merge it?

**Comment by minego** [comment]
I second this.

**Comment by Pickles888** [comment]
@rowanG077 it has been merged
