### ISSUE TITLE
Go to shell after boot

### ISSUE THREAD

**Issue by ImZedik** [tpwrules/nixos-apple-silicon#148]
Accidentally deleted gnome so I can’t login, is there a way to boot, then immediately go to shell?

**Comment by ImZedik** [comment]
I figured it out

**Comment by ImZedik** [comment]
Never mind, it didn’t work

**Comment by diegobfernandez** [comment]
Boot into an old generation? Or you don't even see the boot loader screen listing the generations?
Could you give more details about how you deleted gnome? It also seems like a NixOS question rather than NixOS on Apple Silicon. You might find answers in other NixOS communities/channels.

**Comment by ImZedik** [comment]
@diegobfernandez Yes i figured out that you can do that. I deleted gnome by accidentally removing it in configuration.nix
