### ISSUE TITLE
Update to latest FEDORA ASAHI REMIX linux kernel config.

### ISSUE THREAD

**Issue by liarokapisv** [tpwrules/nixos-apple-silicon#162]
It appears that the kernel config does not include the latest kernel config updates that among other things fix some issues with the energy aware scheduling.

I think the only relevant options are:

```
CONFIG_UCLAMP_TASK=y
CONFIG_UCLAMP_TASK_GROUP=y
CONFIG_UCLAMP_BUCKETS_COUNT=5
```

**Comment by zzywysm** [comment]
This is a fools' errand.  This project has been hostile to kernel changes for a very long time.

https://github.com/tpwrules/nixos-apple-silicon/pull/33
https://github.com/tpwrules/nixos-apple-silicon/pull/113
https://github.com/tpwrules/nixos-apple-silicon/pull/134

**Comment by liarokapisv** [comment]
I think these changes are more inline with @tpwrules 's maintenance policy. I basically did what they usually do and just git diffed the redhat/config directory from the fedora-asahi repo, so they just follow upstream. Anecdotally, these changes increased my pipewire setup 's battery life by 30-40% or so.

**Comment by liarokapisv** [comment]
Same thing here pretty much identical.

**Comment by diegobfernandez** [comment]
Wow, copied the config to my M1 Pro and I got a very nice battery boost. Thanks a lot 🙏

It seems idling or low power tasks demand much less from the CPU, no visual performance impact.

If there are some reason not to merge these configs it would be nice to have that behind an option in the module.

**Comment by tpwrules** [comment]
Apologies for missing this, my diff didn't catch it. These options will be in the next release.

**Comment by zzywysm** [comment]
> Apologies for missing this, my diff didn't catch it. These options will be in the next release.

Technically you missed this when I proposed the exact same config changes on December 27 in pull request 134:

https://github.com/tpwrules/nixos-apple-silicon/pull/134/commits/43ebc3b32e3a0b1cf37fc78404f19cba561b888f
