### ISSUE TITLE
Flake won't build.

### ISSUE THREAD

**Issue by YaroKasear** [tpwrules/nixos-apple-silicon#166]
I am trying to get a Flake working with this after following the documentation to install NixOS. NixOS is up and running but it's not been very good so far with my flake. I am trying to do a `nixos-rebuild` and I get this:

```
error: builder for '/nix/store/ls25myq6chw1csff27nk8cw08w48kijj-linux-6.6.0-asahi.drv' failed with exit code 2;
       last 10 log lines:
       >    |     ^^^^^^^^^^^^^^^^^
       >
       > error: aborting due to previous error; 8 warnings emitted
       >
       > For more information about this error, try `rustc --explain E0432`.
       > make[3]: *** [../rust/Makefile:443: rust/alloc.o] Error 1
       > make[2]: *** [/build/source/Makefile:1208: prepare] Error 2
       > make[1]: *** [/build/source/Makefile:234: __sub-make] Error 2
       > make[1]: Leaving directory '/build/source/build'
       > make: *** [Makefile:234: __sub-make] Error 2
       For full logs, run 'nix log /nix/store/ls25myq6chw1csff27nk8cw08w48kijj-linux-6.6.0-asahi.drv'.
error: 1 dependencies of derivation '/nix/store/8qaly6gl37g5czx6m8hzmpg4i6f3315z-nixos-system-gwyn-linux-24.05.20240224.73de017.drv' failed to build
```

The output of `nix log /nix/store/95iznshxxws2i974xawy3hmqbjsjsbfp-linux-6.6.0-asahi.drv` is attached. It looks like maybe Rust might be too new?

[log.txt](https://github.com/tpwrules/nixos-apple-silicon/files/14397743/log.txt)

**Comment by tpwrules** [comment]
This is related to the use of a too-new nixpkgs version (they changed how Rust support works). It's strongly recommended to use the same nixpkgs version the release uses as this is the tested configuration.

In this specific case, this problem should go away if you add `hardware.asahi.useExperimentalGPUDriver = true;` to your config.

This issue will be corrected in the next release, but I'm currently tracking down boot problems and don't know when that might be.

**Comment by YaroKasear** [comment]
Thank you. For now I'll use the experimental driver as right now I'm not 100% sure how to pass a different nixpkgs version in a flake that uses snowfall-lib.

**Comment by YaroKasear** [comment]
Unfortunately I think I'm going to drop this NixOS install. 

With my regular configuration.nix everything works okay. 

But with my flake, firmware will not load even though I followed the instructions given on the guide. I even dropped the flake back to NixOS 23.11 which brought the kernel to 6.6.0-asahi, the same version as the configuration.nix apparently installs and it still refused to load the firmware.

If I can't use my flake, this is just a dealbreaker. :(
