### ISSUE TITLE
error with the latest sound module: 'The option `services.pipewire.configPackages' does not exist'

### ISSUE THREAD

**Issue by foldfree** [tpwrules/nixos-apple-silicon#167]
i updated apple-silicon-support to the last commit https://github.com/tpwrules/nixos-apple-silicon/commit/75b06b99f9e344b1195f23600201575d45497be8
and since, I cannot rebuild the config anymore.
I get the following error:

```
 error: The option `services.pipewire.configPackages' does not exist. Definition values:
       - In `/nix/store/c4m86vnp3m4yikxrdnd23x1qvvj3m4j5-apple-silicon-support/apple-silicon-support/apple-silicon-support/modules/sound':
           {
             _type = "if";
             condition = true;
             content = [
               <derivation asahi-audio-1.6>
           ...
```

**Comment by rowanG077** [comment]
It's not yet in nixpkgs-unstable. You have to follow the commit set in the flake.

**Comment by foldfree** [comment]
Thanks for the lightning fast reply. 
Does that mean it is just a temporary error? I don't know how to use flakes yet.

**Comment by rowanG077** [comment]
I don't use the flake either. what I did is use a local nix package checkout out at the commit of the flake. It should land in unstable soon I expect. Once it has landed I will switch back to upstream.

Essentially this is what I did:

```
git clone git@github.com:NixOS/nixpkgs.git
cd nixpkgs
git checkout 94cda73bf2fd675de987db7c3ac81e861b892266
cd ../
sudo nixos-rebuild -I nixpkgs=$(pwd)/nixpkgs --upgrade switch
```

**Comment by tpwrules** [comment]
Yes, this is the right answer. Alternately you can wait a day or so. The (missing) PR causing this issue is in fact in nixpkgs-unstable, but not nixos-unstable: https://nixpk.gs/pr-tracker.html?pr=282377 .

Unfortunately the sound change got fumbled a little by nixpkgs and I needed to ship a very recent nixpkgs commit to fix some other issues, so that came along too.

(NB: you can just do `-I nixpkgs=.`, the tools are smart enough to resolve the relative path)

**Comment by tpwrules** [comment]
I'm going to leave this open until the commit lands in the main unstable channel. I might be able to modify the module to work around this too.

**Comment by rowanG077** [comment]
The new config has hit nixos-unstable so you no longer need to use the local nixpkgs.

**Comment by tpwrules** [comment]
I've re-added compatibility with the old way and the new way just in case.
