### ISSUE TITLE
nixos-install fails with "experimental Nix feature is disabled"

### ISSUE THREAD

**Issue by nolight132** [tpwrules/nixos-apple-silicon#169]
Hi, I am new to NixOS. I was able to follow the instructions until ```nixos-install``` command.

Here's the output:

```
copying channel...
building the configuration in /mnt/etc/nixos/configuration.nix...
error: experimental Nix feature 'flakes' is disabled; use '--extra-experimental-features flakes' to override
```

Passing the option to the aforementioned command gave no result. I have also tried setting it in the nix.settings in my configuration.nix, still nothing.

Thanks in advance!

**Comment by tpwrules** [comment]
Please try `--option extra-experimental-features flakes` instead.

**Comment by nolight132** [comment]
That did the trick, thank you. 

I am wondering, my configuration doesn't seem to be unusual in any way, is it the default way of installing NixOS?

**Comment by tpwrules** [comment]
I think there’s a bug causing this message. I noticed it when testing but thought it was something I had done to my system. I’m going to keep this issue open until it’s fixed.

**Comment by tpwrules** [comment]
Added a workaround for now.
