### ISSUE TITLE
When installing a stateless system, it prompts that there is insufficient remaining space.

### ISSUE THREAD

**Issue by ityspace** [tpwrules/nixos-apple-silicon#171]
When installing a stateless system, it prompts that there is insufficient remaining space.

**Comment by tpwrules** [comment]
There is not much to go off here. Please provide more information. What do you mean by a "stateless system"? What does this prompt look like?

**Comment by ityspace** [comment]
When I install the system on a Mac m2 air, I will get an error that lack of space when I mount /mnt on tmpfs and /mnt/nix on /dev/nvme0n1p5 to implement a stateless system. Today it worked. But this problem is not known for some reason.

![2024-03-05-13-28-01-228](https://github.com/tpwrules/nixos-apple-silicon/assets/110728147/029433ea-68e1-49f1-bcb2-a8b0d8925e7a)
