### ISSUE TITLE
Generation select corrupt/incorrect

### ISSUE THREAD

**Issue by TLMcNulty** [tpwrules/nixos-apple-silicon#186]
I'd expect the NixOS generation/GRUB looking menu to be centered, and to display a countdown/menu options as it does in a stock configuration. 

Been looking on the NixOS discourse, netted nothing. My post there - https://discourse.nixos.org/t/corrupted-inappropriate-bootloader-generation-select-text/42393

As detailed there I've run the relevant NixOS steps I could find for regenerating the bootloader. 

Pic:
![PXL_20240320_205110386](https://github.com/tpwrules/nixos-apple-silicon/assets/8993166/b174dec8-4866-41a9-ae1b-73bb8006cc75)

It functions as I'd expect but the menu options at the bottom are dirty.

**Comment by tpwrules** [comment]
This is just how it is. Allegedly there is a U-Boot fix in the pipeline but it hasn't been released to the Fedora Asahi Remix yet so I haven't taken it. It does not bother me much personally. I suppose it could be annoying if you need to edit the command line.

**Comment by TLMcNulty** [comment]
This is a fine answer, thank you! I was concerned I'd been unlucky during setup. I'll refer to u-boot docs and source to investigate further. As it is functional it doesn't bother me much either.

**Comment by tpwrules** [comment]
https://github.com/jannau/u-boot-1/commits/asahi-vidconsole-fixes/
