### ISSUE TITLE
build failure Kernel and Bootstrap Installer

### ISSUE THREAD

**Issue by kavfkah** [tpwrules/nixos-apple-silicon#187]
hey, I was just follow the installation instructions and m1n1 and u-boot build fine, but the Kernel and Bootstrap Installer failed doing: `nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap -o installer -j4 -L`

with this log: https://pastebin.com/veZ4Qmf4

is there anything I can do to fix this?

**Comment by larstiq** [comment]
The logs mentions e.g.
```
./scripts/ocsp-stapling-with-ca-as-responder.test: line 188: nc: command not found
```
and
```
./scripts/ping.test: line 25: ping: command not found
```
so perhaps start by fixing all such not found commands?

**Comment by kavfkah** [comment]
ah okay I just had to add toybox in iso-configuration/installer-configuration.nix and now it's working
