### ISSUE TITLE
Kernel build fails with hash mismatch

### ISSUE THREAD

**Issue by devusb** [tpwrules/nixos-apple-silicon#196]
Started getting hash mismatch when building the kernel. Hash reference is [here](https://github.com/tpwrules/nixos-apple-silicon/blob/4fac534b775aa0c40611257fa19ab8ab3243f4dc/apple-silicon-support/packages/linux-asahi/default.nix#L98).

```
       error: 1 dependencies of derivation '/nix/store/5lqg1wrk36i2w0y0280iyldhwnm5g6jc-references.nix.drv' failed to build
┏━ 1 Errors: 
┃ error: hash mismatch in fixed-output derivation '/nix/store/f4dzc814fnphbkp2ip7hj0fzcbm23bqq-source.drv':
┃          specified: sha256-83AnK/th8nRokeRWen/dTcJdObbB3YwyTxFIH5KGD/A=
┃             got:    sha256-h/xxVpI+954akkA3tgshZrpKTvIpH7Q9N6kbTlVdnjU=
```

**Comment by devusb** [comment]
Never mind -- think I only had this issue building on my Mac -- building on a remote `aarch64-linux` host worked fine. I suspect some kind of filesystem issue on my Mac -- btrfs reports checksum errors, switching to ext4 masked the issue but obviously didn't resolve it. Seems to only happen when I use LUKS but maybe I haven't tried without it long enough for the issue to manifest. Either way, not a hash mismatch -- data corruption on my side. Closing issue.

**Comment by tpwrules** [comment]
Thanks for reporting regardless, GitHub can in certain circumstances change the hash. This shouldn't have been one of those times though and I verified it indeed hasn't been changed.
