### ISSUE TITLE
I wonder this part already baked in nixos-apple-silicon

### ISSUE THREAD

**Issue by dontdieych** [tpwrules/nixos-apple-silicon#198]
Quot from https://asahilinux.org/fedora/,

> The best Linux laptop audio you’ve ever heard
> 
> Over the past two years, we’ve worked hard to pioneer the world’s first fully integrated DSP solution for the desktop Linux ecosystem. Just install Fedora Asahi Remix and enjoy high-quality audio right out of the box, no setup needed. We’ve worked together with the [PipeWire](https://pipewire.org/) and [WirePlumber](https://gitlab.freedesktop.org/pipewire/wireplumber) projects to add support for fully automatic and transparent DSP configuration, and then individually measured and calibrated 8+ different machine models, designing a customized DSP filter configuration for each one.
> 
> With our in-house [Bankstown](https://github.com/chadmed/bankstown) bass boost technology and our own pioneering open source [Smart Amp](https://github.com/AsahiLinux/speakersafetyd) implementation to safely provide full loudness and dynamic range, the result is the best audio you’ve ever heard on a Linux laptop. And we’ve even optimized the scheduling and power consumption of the DSP processing, so you’ll get excellent battery life while playing back audio.

**Comment by rowanG077** [comment]
Yes it is.

**Comment by dontdieych** [comment]
> Yes it is.

Thanks.

**Comment by rowanG077** [comment]
Please close this issue.

**Comment by dontdieych** [comment]
:smiling_face_with_tear:

**Comment by dontdieych** [comment]
:smiling_face_with_tear:
