### ISSUE TITLE
The option `sound' can no longer be used since it's been removed

### ISSUE THREAD

**Issue by CryoMyst** [tpwrules/nixos-apple-silicon#216]
Release notes: https://github.com/K900/nixpkgs/blob/3eeff54780a1a8c73c82ca51987962b62bd4219e/nixos/doc/manual/release-notes/rl-2411.section.md#sound-options-removal-sec-release-2411-migration-sound
Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/326262

Seems we are using it here which causes an errors on unstable.
https://github.com/tpwrules/nixos-apple-silicon/blob/6015c1e2f91896e0b7a983c2824c665af32f568a/apple-silicon-support/modules/sound/default.nix#L14

**Comment by heywoodlh** [comment]
Workaround for people not wanting to dig into source:

```
hardware.asahi.setupAsahiSound = false;
```

**Comment by CryoMyst** [comment]
Or change their input to `url = "github:CryoMyst/nixos-apple-silicon/83437a4794de98a7c5dcc48e5b73c3e50b6d4a3d";` until a fix is merged.

https://github.com/CryoMyst/nixos-apple-silicon/commit/83437a4794de98a7c5dcc48e5b73c3e50b6d4a3d

**Comment by bkchr** [comment]
You can also check out the code locally, remove the line of code and run `nix flake update --override-input NAME_OF_THIS_REPO_IN_YOUR_FLAKES.NIX PATH_TO_THE_CHECKOUT`.

**Comment by tpwrules** [comment]
Thanks for reporting. This has been fixed in the latest release. Please upgrade.
