### ISSUE TITLE
re: mesa: seeking strategies for rebuilding the world

### ISSUE THREAD

**Issue by montchr** [tpwrules/nixos-apple-silicon#217]
First off, disclaimer: this is not a bug report or feature request.  I would have posted this in a GitHub Discussion thread, but they are not enabled for this project.  And I figured that there wouldn't be much point in soliciting advice for such a niche setup in the Discourse (but maybe I'm wrong).

I recently enabled the experimental GPU driver via the `overlay` method (because flakes) and rebuilt the world.  It took a while, of course, and I am _very_ pleased with the results.  However, I'm thinking that the only way I was able to rebuild my system the first time was because I used one of those paid remote-builders services, but I'm not trying to make that a habit.

It probably wouldn't be so bad if I didn't have to build 3+ different versions of `webkitgtk`.  I haven't yet been able to build even _one_ of those derivations without depending on a paid build service because `webkitgtk` requires fine-tuning build settings and I haven't yet found the correct combination to build successfully.  I'm thinking I may just end up making the tradeoff to use the `replace` mode despite the additional complications for a flake-based setup.

So, for those of you that use Asahi Mesa on a flakes-based configuration, I'm wondering: what does your workflow look like?  How often do you update?  How do you minimize excessively-difficult builds like `webkitgtk`?

**Comment by iclanzan** [comment]
I am writing this in case it helps anyone, but I’ve tried repeatedly to “build the world” like this and the build would always eventually fail at compiling `webkitgtk`, `electron` or `chromium`. The build was running out of memory no matter how much swap I threw at it. Adding the `-j 1` flag to force compiling one thing at a time however made everything build successfully!
