### ISSUE TITLE
crashes with kernel >= 6.9.7

### ISSUE THREAD

**Issue by oliverbestmann** [tpwrules/nixos-apple-silicon#218]
I needed to downgrade to 6.9.5 to get a stable system, wayland/gnome completelly freezes after a few minutes. Kernel 6.9.5 is running stable for me for a few weeks now.

See also https://github.com/AsahiLinux/linux/issues/309

**Comment by evfeal** [comment]
> I needed to downgrade to 6.9.5 to get a stable system, wayland/gnome completelly freezes after a few minutes. Kernel 6.9.5 is running stable for me for a few weeks now.
> 
> See also [AsahiLinux/linux#309](https://github.com/AsahiLinux/linux/issues/309)

this happens to me as well, how did you downgrade the kernel to 6.9.5? In the commit history I only see that the latest release was 6.8.10-4

**Comment by montchr** [comment]
> wayland/gnome completelly freezes after a few minutes


I haven't seen the issue in such a severe way, but I'm going to play it safe and downgrade to 6.9.5 (thank you for the fork!).  I finished updating yesterday and things have been fine overall for me on GNOME until a random crash about an hour ago.  When my laptop display froze prior to the auto-reboot, the resource monitor widget didn't show any high usage.

**Comment by tpwrules** [comment]
Would it be best to simply revert to 6.9.5 for now, or even 6.8? Things seemed okay enough on my machine (I wrote the release notes and did all the issue management on the latest release) but the linked issue looks scary.

**Comment by oliverbestmann** [comment]
I am using 6.9.5 as my daily driver for a about two weeks now. But I can understand a downgrade to 6.8. I have the hashes here if you decide to go with 6.9.5: https://github.com/oliverbestmann/nixos-apple-silicon/commit/2a5a7f4337bf09fb929de9d528b381dc1894ab71

**Comment by evfeal** [comment]
> Would it be best to simply revert to 6.9.5 for now, or even 6.8? Things seemed okay enough on my machine (I wrote the release notes and did all the issue management on the latest release) but the linked issue looks scary.

6.9.5 seems to be working in a stable manner for me, at least on my m1 pro. until more issues come up suggesting otherwise, I would say just stick with 6.9.5

**Comment by tpwrules** [comment]
The latest release downgrades to 6.9.5. I plan to keep this open until a resolution is found and we can upgrade again.

**Comment by emilia-miki** [comment]
> The latest release downgrades to 6.9.5. I plan to keep this open until a resolution is found and we can upgrade again.

Not really a fix, but here's an explanation https://social.treehouse.systems/@marcan/112807476204884179

**Comment by cjdell** [comment]
As discussed below, @asahilina has kindly made a workaround for the `drm_sched_can_queue` issue on 6.9.9:
https://github.com/AsahiLinux/linux/issues/309

Kernel commit:
https://github.com/AsahiLinux/linux/commit/fd34a0c8a30d41bfea10829d1f9193f6c9150dc1

I have made a fork of the `nixos-apple-silicon` repo pointing to the new kernel commit:
https://github.com/cjdell/nixos-apple-silicon/commit/cf6ef8b30d0a5979d63c90509bfaeda76ca0fac2

I am about to test. :-)

**Comment by jannau** [comment]
> 
> Not really a fix, but here's an explanation https://social.treehouse.systems/@marcan/112807476204884179

that's a different bug

**Comment by tpwrules** [comment]
I tested the latest Asahi Linux 6.9.9-7 tag for several hours today and was unable to break it. I just did a new release with it, so this should be fixed on our side. Thanks all for the help diagnosing and collaborating with the Asahi folks, it's really helpful.
