### ISSUE TITLE
Built-in speakers broken after nixpkgs update

### ISSUE THREAD

**Issue by waltmck** [tpwrules/nixos-apple-silicon#223]
I'm not entirely sure how to diagnose this problem--after updating nixpkgs to the latest version, sound stops working on the built-in speakers. Sound works fine over Bluetooth headphones, and even more strangely, after connecting Bluetooth headphones I can hear muffled output through the headphones when I play through the built-in speakers.

The only new error in the journal is during boot:
```
wireplumber[2634]: wp-event-dispatcher: <WpAsyncEventHook:0x21fd1660> failed: <WpSiStandardLink:0x21fdd540> link failed: 2 of 2 PipeWire links failed
```

The sink still appears in `wpctl status`, and this is the output of `wpctl inspect`:
```
id 46, type PipeWire:Interface:Node
    alsa.card = "1"
    alsa.card_name = "MacBook Air J413"
    alsa.class = "generic"
    alsa.device = "0"
    alsa.driver_name = "snd_soc_macaudio"
    alsa.id = "AppleJ413"
    alsa.long_card_name = "MacBook Air J413"
    alsa.mixer_device = "_ucm0003.hw:AppleJ413"
    alsa.name = ""
    alsa.resolution_bits = "16"
    alsa.subclass = "generic-mix"
    alsa.subdevice = "0"
    alsa.subdevice_name = "subdevice #0"
    alsa.sync.id = "00000000:00000000:00000000:00000000"
    api.alsa.card.longname = "MacBook Air J413"
    api.alsa.card.name = "MacBook Air J413"
    api.alsa.open.ucm = "true"
    api.alsa.path = "hw:AppleJ413,0"
    api.alsa.pcm.card = "1"
    api.alsa.pcm.stream = "playback"
    audio.channels = "2"
    audio.position = "FL,FR"
    card.profile.device = "1"
  * client.id = "77"
    clock.quantum-limit = "8192"
    device.api = "alsa"
    device.class = "sound"
  * device.id = "76"
    device.profile.description = "Headphones"
    device.profile.name = "HiFi: Headphones: sink"
    device.routes = "1"
  * factory.id = "19"
    factory.name = "api.alsa.pcm.sink"
    library.name = "audioconvert/libspa-audioconvert"
  * media.class = "Audio/Sink"
  * node.description = "Built-in Audio Headphones"
    node.driver = "true"
    node.loop.name = "data-loop.0"
  * node.name = "alsa_output.platform-sound.HiFi__Headphones__sink"
  * node.nick = "Headphones"
    node.pause-on-idle = "false"
  * object.path = "alsa:acp:AppleJ413:1:playback"
  * object.serial = "152"
    port.group = "playback"
  * priority.driver = "1000"
  * priority.session = "1000"
```

What steps should I take to debug this further?

**Comment by maximbaz** [comment]
It might be a silly question, but do you have `hardware.asahi.setupAsahiSound = true` set?

**Comment by waltmck** [comment]
Yes I do--the setup was working perfectly prior to the nixpkgs update. My apple silicon-specific config is [here](https://github.com/waltmck/dotfiles/blob/main/hardware/asahi/default.nix), and there is some additional audio-related config [here](https://github.com/waltmck/dotfiles/blob/main/services/audio/default.nix).

**Comment by vs49688** [comment]
This might not be an `nixos-apple-silicon` issue - I see the exact same behaviour on my x86 machine (recent nixpkgs, pipewire). It's annoying, but a `systemctl --user restart pipewire` fixes it until next boot.

**Comment by waltmck** [comment]
I did see that issue on the NixOS discord, so I tried restarting `pipewire` and other related services (`wireplumber`, `pipewire-pulse`). Unfortunately this does not fix the issue for me. Additionally, does that bug allow external speakers to work prior to restarting `pipewire`?

**Comment by waltmck** [comment]
After updating again updating `nixpkgs` and this project, the issue still persists with the same symptoms.

**Comment by waltmck** [comment]
I was messing around with `coppwr` and notice that the `output_MONO` node of the built-in speakers was actually producing audible sound (this was the muffled sound I heard when setting setting the default sink to the built-in speakers while my headphones were connected. A screenshot of the graph is attached, with the sound being audible through headphones but not the built-in speakers). I believe this means that the problem is in the speaker driver itself--should I file a bug upstream with the Asahi folks?
![2024-09-19_15-06-44](https://github.com/user-attachments/assets/283921de-0e95-4b69-a96b-6e45605819c0)

**Comment by waltmck** [comment]
Some Asahi people on Matrix pointed out that there are some known issues with `libgnome-volume-control` which incorrectly expose the raw speaker interface and might be causing this issue (I am using `ags` which uses `gvc` as a backend). However, I ran the following experiment:

1. Boot to runlevel 3
2. Run `systemctl start --user pipewire`
3. Run `wpctl status`.

The `audio` section of the output looks like this:
```
Audio
 ├─ Devices:
 │      52. Loopback                            [alsa]
 │      53. Built-in Audio                      [alsa]
 │  
 ├─ Sinks:
 │  *   54. Loopback Analog Stereo              [vol: 1.00]
 │      59. Built-in Audio Headphones           [vol: 1.00]
 │  
 ├─ Sources:
 │  *   37. Loopback Analog Stereo              [vol: 1.00]
 │      60. Built-in Audio Headset Microphone   [vol: 1.00]
 │  
 ├─ Filters:
 │    - filter-chain-2722-19                                        
 │      64. audio_effect.j413-convolver                                  [Audio/Sink]
 │      65. effect_output.j413-convolver                                 [Stream/Output/Audio]
 │  
 └─ Streams:
        98. Gapless                                                     
            100. output_FL       > Loopback PCM:playback_FL	[active]
            102. output_FR       > Loopback PCM:playback_FR	[active]
```
which is completely wrong--`pipewire` has set the loopback sink as the default rather than the internal speakers device. The Asahi people seem to think that this should not happen (and the correct sink is indeed selected on the Fedora installation), so this might be a packaging issue (or some weird configuration/state issue on my machine).

**Comment by waltmck** [comment]
After much experimentation I found that `droidcam` was the source of the problem. The issue was fixed by disabling it.
