### ISSUE TITLE
U-boot config step (?) not working (13'' M1 2020) (No steps available after selecting NixOS in boot picker)

### ISSUE THREAD

**Issue by ppenguin** [tpwrules/nixos-apple-silicon#224]
I seem to get stuck just after this step: https://github.com/tpwrules/nixos-apple-silicon/blob/main/docs/uefi-standalone.md#booting-the-installer

After pressing power long for startup options, I can choose "1. NixOS, 2. MacSSD, 3. Options".
But after choosing (1) I see a "MacOS recovery" window where two drives are shown for selection: `/nix/store` (this was from a nix install *under MacOS*, and `MacHD`.

So the follwing does not happen as expected:
> ... and select the new NixOS option in the boot picker. Follow the prompts and enter your administrator password.
I.e. I see no prompts but immediately the recovery startup disk selector.

The previous steps were completed without error, I seem to have several NixOS partitions too, including an EFI one.

How could I troubleshoot this further?

**Comment by damien-biasotto** [comment]
I believe it happened to me once or twice, have you tried to select the MacHD disk, it should resume the installation process IIRC.

**Comment by ppenguin** [comment]
@damien-biasotto Thanks! That did the trick! ... and I was expecting to be presented the boot volume from the USB... Installing now...
