### ISSUE TITLE
Switching to nixos stable?

### ISSUE THREAD

**Issue by dxwil** [tpwrules/nixos-apple-silicon#228]
Must I be on the unstable branch as, from my understanding, configured by the installation or can I downgrade to the stable branch without breaking Asahi support?

**Comment by foldfree** [comment]
It should work. it does to me. You can still roll back if it fails.

**Comment by foldfree** [comment]
Doesn’t work anymore though. I had to switch to unstable with the last release to get GPU acceleration. :smiling_face_with_tear:
