### ISSUE TITLE
Fix Hyprland?

### ISSUE THREAD

**Issue by youwen5** [tpwrules/nixos-apple-silicon#229]
The latest version (0.42.0) of Hyprland in unstable is completely broken on Asahi and all OpenGL applications refuse to open (see [this issue for more info](https://github.com/hyprwm/Hyprland/issues/7364)). The lead developer said that the fix is not likely to release until 0.43.0.

Can we patch it here to allow it to work properly or is that out of scope for this project? I currently have an overlay applying [this patch](https://github.com/youwen5/liminalOS/blob/asahi-fix/hosts/callisto/asahi-fix.patch) I made to the Hyprland package which allows it to function properly.

**Comment by rowanG077** [comment]
Why not just make a PR for upstream. In my experience nixpkgs has no problem carrying such patches.

**Comment by arminius-smh** [comment]
Not sure if you're aware of this, but in the meantime you could also add Hyprland as an input and follow git, if you don't want to apply any patches: https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/ (see Flakes option)

**Comment by youwen5** [comment]
> Not sure if you're aware of this, but in the meantime you could also add Hyprland as an input and follow git, if you don't want to apply any patches: https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/ (see Flakes option)

I tried that but it crashed on startup because of mismatched mesa driver versions. Afaik asahi brings its own mesa so I'm not sure how to avoid that. Did you get it working?

**Comment by arminius-smh** [comment]
Yeah I've used it for about a year now, but I never had an issue regarding mismatched mesa versions, so sadly I don't know anything about that to fix it, only relevant options I see regarding asahi I have set are
```
  hardware = {
    asahi = {
      enable = true;
      peripheralFirmwareDirectory = ./firmware;
      useExperimentalGPUDriver = true;
      experimentalGPUInstallMode = "replace";
      setupAsahiSound = true;
    };
```
Otherwise my setup is exactly like the wiki, but no messing with any mesa packages or anything like that

**Comment by zvolin** [comment]
That's a really big patch, for me it's enough to just apply [this single commit](https://github.com/zvolin/nixos-config/blob/main/overlays/0001-linux-dmabuf-allow-on-split-node-systems.patch) (rebased on 0.42) for hyprland to work

**Comment by zvolin** [comment]
The patch above patch was submitted upstream https://github.com/NixOS/nixpkgs/pull/337203, so this can be closed
