### ISSUE TITLE
GPU Driver Issue with Hyprland?

### ISSUE THREAD

**Issue by themg95** [tpwrules/nixos-apple-silicon#230]
I just installed nixos and hyprland on my m2 mbp but when i try to run hyprland, i get a blank screen and an error that says:
`(EE) could not connect to wayland serverd1 (Device or resource busy)so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri/)dri)`

**Comment by themg95** [comment]
Partially solved the issue by enabling 
`hardware.asahi.useExperimentalGPUDriver` but now hyprland is kinda buggy and i have to pass --impure when building because of pure evaluation mode

**Comment by GhostPHX** [comment]
See solved Issue #229

**Comment by themg95** [comment]
> See solved Issue #229

yeah, saw that issue but i still have the issue and the patch seems to have been merged to nixpkgs

**Comment by themg95** [comment]
ok i fully fixed the issue. when i clicked my touchbar, i realized that the cursor moved and that hyprland was trying to extend the screen to the touchbar. i then installed tiny-dfr and voila! all the flickering and stuff gone!

**Comment by tpwrules** [comment]
Should be fixed with the updated nixpkgs in the latest release.
