### ISSUE TITLE
attribute `mesaPlatforms` missing

### ISSUE THREAD

**Issue by Pickles888** [tpwrules/nixos-apple-silicon#233]
I'm getting an error rebuilding my system as of today. After updating my flake, it says `lib.platforms.mesaPlatforms` does not exist in `{apple silicon support}/packages/mesa-asahi-edge/vendor/default.nix` on line 539. I am unable to find any documentation on lib.platforms so I could not fix it myself.

**Comment by rowanG077** [comment]
There is a PR to fix that: https://github.com/tpwrules/nixos-apple-silicon/pull/231

**Comment by tpwrules** [comment]
Fixed in the latest release.
