### ISSUE TITLE
Incompatible with Hive framework

### ISSUE THREAD

**Issue by itypiece** [tpwrules/nixos-apple-silicon#236]
https://github.com/divnix/hive

The Hive framework requires that overlays be centralized in bee.pkgs.overlays

For example,

```nix
  bee = {
    system = "aarch64-linux";
    pkgs = import inputs.nixpkgs {
      inherit (inputs.nixpkgs) system;
      config.allowUnfree = true;
      overlays = [
        inputs.lix-module.overlays.default
      ];
    };
    home = inputs.home-manager;
  };
```
But I don't know what to do with the apple-silicon-support module in this case.

I try to add inputs.apple-silicon-support.overlays.default to it, but there will be a problem, prompting that there are overlays in modules/default.nix.

**Comment by mogery** [comment]
> It is forbidden to modify this readme → read the code!

Good luck finding anyone to support that lol
