### ISSUE TITLE
Asahi kernel module does not build on 24.05

### ISSUE THREAD

**Issue by RossComputerGuy** [tpwrules/nixos-apple-silicon#240]
Updated my Flake to use the latest nixos-apple-silicon commit and 24.05. Ran into a problem where Hyprland isn't starting, `/dev/dri/renderD128` doesn't exist. `lsmod` doesn't show the Asahi module. Using find in the kernel modules directory turns up no results. I probed the kernel config derivation and see `CONFIG_DRM_ASAHI=m` and `CONFIG_RUST=y` so it should be building the kernel module.

**Comment by rowanG077** [comment]
Dup of https://github.com/tpwrules/nixos-apple-silicon/issues/234

**Comment by RossComputerGuy** [comment]
This one seems different because I have the Asahi mesa driver, I can load up wlroots based compositors. `drm_info` works.

**Comment by rowanG077** [comment]
Interesting. Then fixing this @lukaslihotzki does not work by manually updating rust?

> The issue probably is that NixOS 24.05 ships Rust 1.77, but kernel 6.10 requires Rust 1.78 for CONFIG_RUST. Therefore, CONFIG_RUST is disabled when building the current kernel on 24.05. This can be verified with zcat /proc/config.gz | grep CONFIG_RUST (empty with 24.05, set to yes with unstable).

**Comment by RossComputerGuy** [comment]
I'm not sure, I don't get any sort of errors despite having `CONFIG_RUST=y` set already. I would've expected it to throw an error and fail if that is the case.

**Comment by tpwrules** [comment]
It unfortunately won't throw an error, though it could be modified to.

As mentioned, stable support is on a best-effort basis. 24.11 is almost here so I do not plan to address this. If you need graphics acceleration before then, please downgrade the Apple Silicon support module.
