### ISSUE TITLE
Attempting to build config with Hyprland returns CMake build error (M2 MacBook Pro)

### ISSUE THREAD

**Issue by HotPotato451** [tpwrules/nixos-apple-silicon#242]
As the title says. I have zero idea what could be causing this, since I looked through the issues and didn't find anyone with my problem. Does Hyprland just not work? i've attached my config and the log from when I try to build below.

[configuration.nix.txt](https://github.com/user-attachments/files/17345871/configuration.nix.txt)
[log.txt](https://github.com/user-attachments/files/17345873/log.txt)

**Comment by rowanG077** [comment]
upstream issue that is fixed: https://github.com/NixOS/nixpkgs/issues/338985
