### ISSUE TITLE
Adding nixos-apple-silicon channel after fresh install

### ISSUE THREAD

**Issue by EdvardSire** [tpwrules/nixos-apple-silicon#249]
I just did a complete reinstall and wanted to start following the `apple-silicon-support` channel instead of using the local files. I'm unsure whether or not this issue belongs here.

1. Install with ISO
2. Add small changes to `/etc/nixos/configuration.nix`
3. `nixos-rebuild switch`
4. Attempt to add channel:
```
[root@nixos:~]# nix-channel --list 
nixos https://nixos.org/channels/nixos-unstable

[root@nixos:~]# nix-channel --add https://github.com/tpwrules/nixos-apple-silicon/archive/main.tar.gz apple-silicon-support


[root@nixos:~]# nix-channel --list
apple-silicon-support https://github.com/tpwrules/nixos-apple-silicon/archive/main.tar.gz
nixos https://nixos.org/channels/nixos-unstable

[root@nixos:~]# nix-channel --update apple-silicon-support
this derivation will be built:
  /nix/store/0mx0cpzrn9qr4z73l1b9m4zg119inkc8-apple-silicon-support.drv
building '/nix/store/0mx0cpzrn9qr4z73l1b9m4zg119inkc8-apple-silicon-support.drv'...
error: '/nix/var/nix/profiles/per-user/root/channels/nixos' is not a symlink
```

How should i resolve this? From what I understand I can not run a `nix-channel --update`, the solution I'm finding online, because of #248 and systemd.
Best regards

**Comment by tpwrules** [comment]
The latest release should be fixed for recent nixpkgs. I am not sure why you might get this error off the top of my head, but upgrading is safe now.
