### ISSUE TITLE
Latest release fails to boot due to not mounting root volume

### ISSUE THREAD

**Issue by marcusramberg** [tpwrules/nixos-apple-silicon#258]
![image](https://github.com/user-attachments/assets/ddf5018c-6dfe-4c20-91ac-f97bdc889281)) 
![image](https://github.com/user-attachments/assets/fadb8b54-3f55-4227-9dae-7b9a0817beba)

(This is on a m1 studio max without luks)

**Comment by tpwrules** [comment]
Are there any nvme devices in /dev? Does dmesg show anything useful?

**Comment by marcusramberg** [comment]
The system is frozen after this so I can't check anything. If I boot the previous gen the device is there.

**Comment by youwen5** [comment]
After `git bisect`, I determined that [f71ed35](https://github.com/tpwrules/nixos-apple-silicon/commit/f71ed356c3006234644e14725989634fca042d83) which upgraded kernel version introduces the boot failure (system hangs on mounting root / LUKS decryption).

Sidenote for #257, Plymouth does not work on any commit after `e837fbb`, which is the earliest commit I tested. If I have time later, I may bisect again to try to figure out exactly when Plymouth broke.

**Comment by tpwrules** [comment]
> After `git bisect`, I determined that [f71ed35](https://github.com/tpwrules/nixos-apple-silicon/commit/f71ed356c3006234644e14725989634fca042d83) which upgraded kernel version introduces the boot failure (system hangs on mounting root / LUKS decryption).

Can you revert the changes to the kernel config? Does that help?

**Comment by gender-combinator** [comment]
I'm also encountering this issue. (Same message "A start job is running..." while it hangs on the root/luks partitions, never asking for a password.)

@tpwrules , I reverted those changes to the kernel config (apple-silicon-support/packages/linux-asahi/config), but no luck. It's still hanging for me.

**Comment by gender-combinator** [comment]
Some notes: 
- this only happens for me when systemd is enabled in initrd (boot.initrd.systemd.enable). 
- also tried asahi-6.12.3-1, no luck

**Comment by marcusramberg** [comment]
> Some notes: 
> 
> - this only happens for me when systemd is enabled in initrd (boot.initrd.systemd.enable). 
> 
> - also tried asahi-6.12.3-1, no luck

I also have this enabled.

**Comment by tpwrules** [comment]
> this only happens for me when systemd is enabled in initrd (boot.initrd.systemd.enable).

I had suspected, thanks for confirming. Will see if I can replicate.

**Comment by crawfordlong** [comment]
For what it's worth, I just downloaded the latest update from here, ran my update as usual, and I failed to complete a rebuild successfully when trying to restart systemd. When rebooting, I _also_ experienced this issue, but it doesn't seem to be tied specifically to booting. Happy to provide any additional troubleshooting information if you need it.

**Comment by AndreasHGK** [comment]
Can confirm this happens to me too on m1 max macbook pro

**Comment by crawfordlong** [comment]
This one is weird. I can now do a successful `nixos-rebuild switch` without any errors, but when I reboot I get this error, which is a change in behavior from 2 weeks ago. This is also defying my search engine efforts because I'm not exactly sure what is going on.

**Comment by andre4ik3** [comment]
If you boot with debug, disabled plymouth, and redirect journald to console, you can see the true cause is that it's failing to load kernel modules, in particular btrfs. Then it times out waiting for a device that will never show up (because the relevant kernel modules never get loaded), and then it gets stuck on the emergency prompt. It's waiting for input, however no input will ever come (because the relevant kernel modules for keyboard input never get loaded), so it looks like it's frozen. I suspect it loads them in alphabetical order or something, so when btrfs fails, no other modules get loaded. Maybe it's possible to compile a kernel without btrfs if it's not used, however all my systems are on btrfs so it's not really an option 🥲

![image](https://github.com/user-attachments/assets/f139fc22-538b-4e49-8db9-b1632471d725)

**Comment by 0x280** [comment]
i can confirm the same issue on my m1 air (not using btrfs, but luks2 with ext4 partitions)

**Comment by waltmck** [comment]
I can also confirm the same issue on an m2 air with ext4 on luks2.

**Comment by jannau** [comment]
Some config changes (and context) in f71ed356c3006234644e14725989634fca042d83 looks bad. I'm not sure if `CONFIG_APPLE_MAILBOX` and `CONFIG_APPLE_RTKIT` still need to be built-in for rust / gpu support. `CONFIG_APPLE_PLATFORMS` should be set. Not set `CONFIG_SND_SOC_CS42L84` would break headset/headphone audio and not set `CONFIG_TOUCHSCREEN_APPLE_Z2` would break touchbar support.
I don't know but I don't think these are causing the issues. The expected values seems to be still present. I'd suggest a kernel config sanitation step before check-in or checking in the actual `.config` from a kernel build. This doesn't look related to the issue though.

The issue looks like a kernel module availability / loadability issue. Can some either stop in the initramfs (for dracut adding `rd.break=pre-pivot` to the kernel command line) or use `init=/bin/sh` and provide the output of `lsmod`?

**Comment by andre4ik3** [comment]
Adding neither `init=/bin/sh` (replacing existing `init=/nix/store/.../init`, also tried `init=/nix/store/.../sw/bin/sh`) nor `rd.break=pre-pivot` seem to work for me, it still results in the same error. Also of note, the "exec format error" usually suggests a mismatched kernel version or architecture that the modules were compiled for (e.g. kernel is `arm64 6.12.1-asahi` while modules were compiled for older kernel or different architecture/page size?). Here is my full systemd-boot loader entry for reference:

```
title NixOS
sort-key nixos
version Generation 53 NixOS Warbler 25.05.20241219.72e6d67 (Linux 6.12.1-asahi), built on 2024-12-22
linux /EFI/nixos/08110rjlrinva8mj74h1x53krd6k0b7a-linux-6.12.1-asahi-Image.efi
initrd /EFI/nixos/h129x4xbys0x740h9sr21wwyj65p9a1a-initrd-linux-6.12.1-asahi-initrd.efi
options init=/nix/store/f3j9mxmqkvvmmhnybkz6ssql823jp7jw-nixos-system-pluto-25.05.20241219.72e6d67/sw/bin/sh earlycon console=ttySAC0,115200n8 console=tty0 boot.shell_on_fail nvme_apple.flush_interval=0 psi=1 root=fstab loglevel=4 crashkernel=128M nmi_watchdog=panic softlockup_panic=1 systemd.log_level=notice debug systemd.journald.forward_to_console=1
machine-id (redacted)
```

**Comment by tpwrules** [comment]
Happy Decemberween! I finally dug in and figured it all out (not neglecting the holiday). Upgrading to 6.12 changed the config options to enable module compression so modules didn't get compressed. Systemd in initrd strips all ELF files put in the initrd (which includes uncompressed modules), but that breaks them. So the disk drivers couldn't load and the system couldn't boot.

Fixed release that re-enables the compression coming shortly.

@jannau thanks for the input, the way the kernel config is currently managed is rather... bad. But the end result should be right with respect to those options.

I need to work with upstream NixOS on a better way to manage it that doesn't result in builds taking an hour.
