### ISSUE TITLE
Boot process regularly hangs at "starting systemd-udevd version..."

### ISSUE THREAD

**Issue by malte-v** [tpwrules/nixos-apple-silicon#40]
My M2 MBA often fails to boot with the new GPU driver (not sure if it's actually related to the GPU driver, but this was the major update that introduced the issue). The boot process hangs at "starting systemd-udevd version..." and after a couple of seconds, the system reboots. Sometimes this bootloop continues for 3-4 iterations, and some other times the issue does not occur at all. I believe that fiddling around in systemd-boot to delay the boot process prevents the issue somewhat reliably, so there may a hardware initialization race condition causing this problem.

**Comment by tpwrules** [comment]
What `hardware.asahi` options do you have enabled?

I did have one failed boot in my various experimentation and testing with the GPU stuff but it did not automatically reboot. I wonder if you could turn up the console log level and/or video the screen to see if you get a panic log or something.

**Comment by psanford** [comment]
I've also seen a few boot failures since enabling the gpu driver. This was what the console log was showing for one of them: https://gist.github.com/psanford/918bba69d22923a947c81dcee47c2e73

**Comment by tpwrules** [comment]
@psanford Strange, this appears to mention that it failed to start the MTP coprocessor, which AFAIK handles the trackpad on M2 devices specifically. I can't imagine that being related to the GPU changes, but IIRC it is a race condition the Asahi folks have been trying to fix. I asked about it but haven't got anything back yet.

I did get another boot failure with the GPU drivers enabled while preparing the latest release, but it was not in the process of starting systemd. The machine appeared completely hung and I could not change VTs to gather logs.

**Comment by malte-v** [comment]
i don't experience this issue anymore, so i'm going to close this for now. please feel free to reopen if others still have this problem!
