### ISSUE TITLE
m2 mac mini

### ISSUE THREAD

**Issue by kaihendry** [tpwrules/nixos-apple-silicon#50]
Any ideas if it will work with https://www.youtube.com/watch?v=cneoANZKBGk since I am thinking of upgrading my home server to this.

**Comment by tpwrules** [comment]
That depends almost entirely when the Asahi Linux project is able to add support. My work is mostly a repackaging of theirs. I don't think there is major work to do for the M2 Mini in particular, but someone still needs to receive the machine and test. I would guesstimate support might come in a few weeks.

**Comment by rowanG077** [comment]
perhaps consider renaming this project to nixos-asahi or something.

**Comment by tpwrules** [comment]
Should be supported now. Please open an issue if you encounter problems.
