### ISSUE TITLE
Pure nix regex parser for the kernel config

### ISSUE THREAD

**Issue by oati** [tpwrules/nixos-apple-silicon#51]
The kernel package currently depends on an IFD (import from derivation) to parse the kernel config file.

The file is simple enough that it should be easily doable using pure nix with filter, map, regex match, etc.

This should be upstreamed to nixpkgs if resolved.

**Comment by tpwrules** [comment]
That would be fantastic, I never liked the IFD there and it would resolve the `localPkgs` hack.

Is this something you intend to tackle now that the reorganization has been merged? If not, I will try to play with it at some point.

**Comment by oati** [comment]
I have a friend who's been wanting to work on this. I think they'll work on a PR soon.

**Comment by anna328p** [comment]
See https://github.com/tpwrules/nixos-apple-silicon/pull/70#issuecomment-1537622456
