### ISSUE TITLE
Advice NixOS version

### ISSUE THREAD

**Issue by stefan0102** [tpwrules/nixos-apple-silicon#56]
Hello,

My advise don't use NixOS version 23.05 at this moment, but 22.11.

I notice that many things are still not running smoothly on version 23.05 to unstable, using your own software in combination with the nixpkgs system, you sometimes get very strange errors, as one of the examples.

Back to version 22.11 no problem at all and everything runs as it should.

**Comment by tpwrules** [comment]
I only have the bandwidth to test on the unstable channel. Is there some specific issue you encounter with 23.05 that I can fix? If not, then 22.11 should be largely compatible if you prefer to use it.
