### ISSUE TITLE
How to avoid --impure with flakes?

### ISSUE THREAD

**Issue by ingenieroariel** [tpwrules/nixos-apple-silicon#59]
I have been using the flake distro for a few weeks and consider it fantastic. However I do not know how to avoid using `--impure` when building the system. 

I get the following error when `--impure` is not passed:
```
error: cannot look up '<nixos-config>' in pure evaluation mode (use '--impure' to override)

       at /nix/store/ld9ihawdpciw50x3h0kzjzk4c8vy0vkb-source/nixos/modules/system/activation/top-level.nix:317:68:

          316|         config.system.copySystemConfiguration
          317|         ''ln -s '${import ../../../lib/from-env.nix "NIXOS_CONFIG" <nixos-config>}' \
             |                                                                    ^
          318|             "$out/configuration.nix"
(use '--show-trace' to show detailed location information)
```

**Comment by tpwrules** [comment]
I don't think this is an issue in nixos-apple-silicon. The context suggests that you have `system.copySystemConfiguration` enabled somewhere in your config. This is not enabled in my modules.

**Comment by ingenieroariel** [comment]
I don't have access to that specific system but if it does not happen for you I will close it out. I thought it was related to the firmware files not being accessible in the Nix sandbox. Perhaps I should just add the firmware files to the private git repo that manages my flake.

**Comment by tpwrules** [comment]
Please see the information about `hardware.asahi.peripheralFirmwareDirectory` in the guide.

**Comment by MaximilianGaedig** [comment]
I just wanted to mention a solution for people wondering how to keep your flake pure:
```nix
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-23.11";
    apple-silicon-support.url = "github:tpwrules/nixos-apple-silicon";
    # add such a local input:
    asahi-firmware = {
      url="/etc/nixos/firmware";
      flake = false;
    };
  };
```
then, whereever you configure hardware, for example `configuration.nix`:
```nix
# at the top make sure to include inputs
{ [...], inputs, ... }:

{
[...]
# then you can use the input as the firmware directory like this:
    hardware.asahi.peripheralFirmwareDirectory = inputs.asahi-firmware;
[...]
}
```
