### ISSUE TITLE
Installer can't mount /dev/root on MBP M1

### ISSUE THREAD

**Issue by nik012003** [tpwrules/nixos-apple-silicon#60]
Hello, I'm facing the same exact problem as #17  .
After dd'ing the generated iso to the usb drive and successfully booting grub and the kernel, it prints:
`mount: mounting /dev/root on /mnt-root/iso failed: No such file or directory`
I tried unplugging and replugging the usb while in the interactive shell, and it's recognized as /dev/sda, but I can't mount and fdisk says:
`Disk /dev/sda doesn't contain a valid partition table`

EDIT: using the .iso from the releases worked fine, so it's either an issue with my build or the newer versions of the packages included in the latest build process

**Comment by tpwrules** [comment]
How exactly did you build the .iso? Did you use the same nixpkgs version as the release?

The release .iso might have worked by chance. This failure to mount is intermittent in my experience, even with the same computer, .iso, and flash drive.

**Comment by nik012003** [comment]
I followed the steps defined here: https://github.com/tpwrules/nixos-apple-silicon/blob/main/docs/uefi-standalone.md
Executed those commands on arch linux on arm.

**Comment by tpwrules** [comment]
I followed those steps exactly on my M1 Max MBP and got four successful boots and one failed boot. There must be a race condition or timing issue. It sounds like you did nothing wrong, you just got unlucky and didn't try again. There's not much I can do about that.

**Comment by theoparis** [comment]
I'm running into this same problem with a M2 MB, but I got this instead of no such file or directory: `mount: mounting /dev/loop0 on /mnt-root/nix/.ro-store failed: invalid argument`.

**Comment by theoparis** [comment]
Should I create a new issue? I can't seem to get a (samsung) usb c flash drive to work at all  and a usb type a via an adapter works but it fails with the above invalid argument error...
