### ISSUE TITLE
Xorg with Nixos on an M1 macbook air seems to be very sluggish.

### ISSUE THREAD

**Issue by Aspectsides** [tpwrules/nixos-apple-silicon#83]
I wrote up a basic home-manager + nix flake config for my m1 mac, and i'm using the same awesomewm config as what i used on regular asahi alarm. however, awesome on Nixos is noticeably slower, with workspace switching taking upwards of 1 second and the CPU usage of X spiking up to 50% every time a window is opened. Programs that used to work perfectly in asahi alarm, such as alacritty, now cant seem to use the graphics driver as they run very slowly. I have opengl and the edge kernel enabled, the relevant part of the config [here](https://github.com/Aspectsides/dotfiles/blob/786f86fa3d8e0d47c24eaac5efb55507b0d4d2a1/nixos/starfall/configuration.nix#L169-L173)

I would really appreciate if someone could tell me exactly what I'm doing wrong,

**Comment by psanford** [comment]
I don't see `hardware.asahi.useExperimentalGPUDriver = true;` set in your config.

**Comment by psanford** [comment]
If you run `glxinfo` you can see the current driver being used. `llvmpipe` is the cpu renderer. `Apple ...` will be the gpu:
```
# cpu renderer
$ glxinfo  | grep 'OpenGL renderer string'
OpenGL renderer string: llvmpipe (LLVM 15.0.6, 128 bits)

# gpu renderer
$ glxinfo  | grep 'OpenGL renderer string'
OpenGL renderer string: Apple M2 (G14G B0)
```

**Comment by shayne** [comment]
I use `none+i3` and have a pretty sluggish experience. However, Firefox has proper GL acceleration (tested via WebGL). I reconfigured things to use a proper DE, which was smooth. I haven't spent the time to figure out what's going on with i3.
