### ISSUE TITLE
question: is there ever a need to update the proprietary firmware during normal operation?

### ISSUE THREAD

**Issue by montchr** [tpwrules/nixos-apple-silicon#87]
Aside from during initial installation and during recovery/rescue, do I need to be mindful of updates to the non-free/non-redistributable firmware? The docs say the only way to update this firmware is via the EFI partition and that it doesn't change unexpectedly. Is there any situation where I must/should update the firmware, e.g. after a macOS system upgrade?

For context, if it matters, I am using flakes and have the proprietary firmware stored in a private git repo and included as a flake input for setting the path to the `hardware.asahi.peripheralFirmwareDirectory`. So, if something changed, I would need to update the private repo manually. 

I only ask for my own peace of mind so that I don't accidentally break something through ignorance. If this is not a silly question, perhaps the answer could be added as a note in the docs?

**Comment by tpwrules** [comment]
The firmware is set up by the Asahi installer and specific to the macOS version the Asahi installer has used. To my knowledge, this has not changed for a particular machine since the first official alpha release of the installer back in early 2022.

Therefore, there's no update to be done yet. If this changes in the future I will update the docs.

**Comment by montchr** [comment]
Good to know, thanks for confirming!

Excellent job by the way – I had absolutely no issues following the guide.

**Comment by bkchr** [comment]
@tpwrules don't we need a way now to update the firmware now? To get the webcam blob?

**Comment by tpwrules** [comment]
Unfortunately there is no official way to do this still.

There are manual instructions available from upstream for this specific case [here](https://discussion.fedoraproject.org/t/webcam-users-manual-action-needed-for-full-image-quality/92027) and the necessary actions were called out in the nixos-apple-silicon release notes (though I didn't have the link available to put in at the time).

I have some plans to be able to do this automatically through Nix but haven't had time to work on them properly.

**Comment by bkchr** [comment]
Ahh at least there are some manual instructions! Ty!
