### ISSUE TITLE
kernel build error on nixpkgs 2023-09-07

### ISSUE THREAD

**Issue by idm1try** [tpwrules/nixos-apple-silicon#99]
![image](https://github.com/tpwrules/nixos-apple-silicon/assets/93399072/a1e6cb02-28d2-4d91-ab04-f56bfeb16981)

and more info:
![image](https://github.com/tpwrules/nixos-apple-silicon/assets/93399072/8712222e-be6d-46bf-8987-a4fb8ed859b2)

**Comment by tpwrules** [comment]
Fixed in the latest release which includes PR #98 .
